# Generated by Django 2.2.16 on 2022-11-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
